// companies.js — Extended ticker → CT.gov sponsor search term
// Loaded before api.js. Entries here are the fallback for tickers not in
// TICKER_TO_SPONSORS. Values are the shortest reliable string that CT.gov's
// query.spons will match against (fuzzy text search on sponsor name field).

window.EXTRA_COMPANIES = {
  // ── Large-cap biotech / specialty pharma ─────────────────────────────────
  BMRN: "BioMarin Pharmaceutical",
  ARGX: "argenx",
  ALNY: "Alnylam Pharmaceuticals",
  ALKS: "Alkermes",
  HZNP: "Horizon Therapeutics",
  JAZZ: "Jazz Pharmaceuticals",
  UTHR: "United Therapeutics",
  NKTR: "Nektar Therapeutics",
  INCY: "Incyte",
  EXEL: "Exelixis",
  NBIX: "Neurocrine Biosciences",
  AGIO: "Agios Pharmaceuticals",
  ACAD: "ACADIA Pharmaceuticals",
  IONS: "Ionis Pharmaceuticals",
  ARWR: "Arrowhead Pharmaceuticals",

  // ── Oncology ─────────────────────────────────────────────────────────────
  KPTI: "Karyopharm Therapeutics",
  MGNX: "MacroGenics",
  IMGN: "ImmunoGen",
  AGEN: "Agenus",
  SMMT: "Summit Therapeutics",
  TGTX: "TG Therapeutics",
  GTHX: "G1 Therapeutics",
  SYRS: "Syros Pharmaceuticals",
  IDYA: "IDEAYA Biosciences",
  RAPT: "RAPT Therapeutics",
  LYEL: "Lyell Immunopharma",
  ALXO: "ALX Oncology",
  STRO: "Sutro Biopharma",
  ORIC: "Oric Pharmaceuticals",
  IMTX: "Immatics",
  NBTX: "Nanobiotix",
  BCYC: "Bicycle Therapeutics",
  EPZM: "Epizyme",
  ATRA: "Atara Biotherapeutics",
  MRUS: "Merus",
  PRME: "Prime Medicine",
  TYRA: "Tyra Biosciences",
  DAWN: "Day One Biopharmaceuticals",
  DCPH: "Deciphera Pharmaceuticals",
  SPPI: "Spectrum Pharmaceuticals",
  SGEN: "Seagen",
  KURA: "Kura Oncology",
  RCKT: "Rocket Pharmaceuticals",
  OCGN: "Ocugen",
  GPCR: "Structure Therapeutics",
  ITOS: "iTeos Therapeutics",
  JANX: "Janux Therapeutics",
  ACET: "Adicet Bio",
  ALLK: "Allakos",
  ALPN: "Alpine Immune Sciences",
  ALDX: "Aldeyra Therapeutics",
  ANNX: "Annexon Biosciences",
  ASMB: "Assembly Biosciences",
  ABCL: "AbCellera Biologics",
  PULM: "Pulmatrix",
  IKTX: "Ikena Oncology",
  KDNY: "Chinook Therapeutics",
  PMVP: "PMV Pharmaceuticals",
  ONCT: "Oncternal Therapeutics",
  KRON: "Kronos Bio",
  MDNA: "Medicenna Therapeutics",
  EDSA: "Edesa Biotech",
  CABA: "Cabaletta Bio",
  XBIA: "Xilio Therapeutics",
  ZNTL: "Zentalis Pharmaceuticals",
  LRMR: "Larimar Therapeutics",
  IMVT: "Immunovant",
  IMCR: "Immunocore",
  KYMR: "Kymera Therapeutics",
  NRIX: "Nurix Therapeutics",
  TNGX: "Tango Therapeutics",
  RLAY: "Relay Therapeutics",
  ERAS: "Erasca",
  NUVL: "Nuvalent",

  // ── Neurology / CNS ───────────────────────────────────────────────────────
  AXSM: "Axsome Therapeutics",
  ITCI: "Intra-Cellular Therapies",
  LBPH: "Longboard Pharmaceuticals",
  MNMD: "Mind Medicine",
  OVID: "Ovid Therapeutics",
  RLMD: "Relmada Therapeutics",
  SAVA: "Cassava Sciences",
  VNDA: "Vanda Pharmaceuticals",
  CERE: "Cerevel Therapeutics",
  BHVN: "Biohaven",
  PRAX: "Praxis Precision Medicines",
  SAGE: "Sage Therapeutics",
  BIIB: "Biogen",
  DNLI: "Denali Therapeutics",
  ALEC: "Alector",
  ATNM: "Actinium Pharmaceuticals",
  NRXP: "NRx Pharmaceuticals",

  // ── Rare disease / genetics ───────────────────────────────────────────────
  ASND: "Ascendis Pharma",
  BBIO: "BridgeBio Pharma",
  BLUE: "bluebird bio",
  SRPT: "Sarepta Therapeutics",
  RARE: "Ultragenyx Pharmaceutical",
  FOLD: "Amicus Therapeutics",
  BEAM: "Beam Therapeutics",
  EDIT: "Editas Medicine",
  CRSP: "CRISPR Therapeutics",
  NTLA: "Intellia Therapeutics",
  QURE: "uniQure",
  SLDB: "Solid Biosciences",
  TRDA: "Entrada Therapeutics",
  TVTX: "Travere Therapeutics",
  PLRX: "Pliant Therapeutics",
  PRTA: "Prothena",
  PTCT: "PTC Therapeutics",
  RYTM: "Rhythm Pharmaceuticals",
  PHAT: "Pharvaris",
  GERN: "Geron Corporation",
  KRYS: "Krystal Biotech",
  GRTS: "Gritstone Bio",
  SNDX: "Syndax Pharmaceuticals",
  MGTX: "MeiraGTx",
  MIRM: "Mirum Pharmaceuticals",
  LEGN: "Legend Biotech",
  YMAB: "Y-mAbs Therapeutics",
  RXRX: "Recursion Pharmaceuticals",
  SPRB: "Spruce Biosciences",

  // ── Immunology / inflammation ─────────────────────────────────────────────
  ANAB: "AnaptysBio",
  APLS: "Apellis Pharmaceuticals",
  ARDX: "Ardelyx",
  ARQT: "Arcutis Biotherapeutics",
  SELB: "Selecta Biosciences",
  XNCR: "Xencor",
  CLDX: "Celldex Therapeutics",
  VRDN: "Viridian Therapeutics",
  HOOK: "Hookipa Pharma",
  ALLO: "Allogene Therapeutics",
  ROIV: "Roivant Sciences",
  ARVN: "Arvinas",

  // ── Cardiology / metabolic ────────────────────────────────────────────────
  ETNB: "89bio",
  MDGL: "Madrigal Pharmaceuticals",
  VKTX: "Viking Therapeutics",
  VRNA: "Verona Pharma",
  AMRN: "Amarin Corporation",
  AKBA: "Akebia Therapeutics",
  LXRX: "Lexicon Pharmaceuticals",
  ESPR: "Esperion Therapeutics",
  KMPH: "Coeptis Therapeutics",

  // ── Gene / cell therapy ───────────────────────────────────────────────────
  AUTL: "Autolus Therapeutics",
  CLLS: "Cellectis",
  VERV: "Verve Therapeutics",
  RNA:  "Avidity Biosciences",
  GRPH: "Graphite Bio",
  SANA: "Sana Biotechnology",
  ORCA: "Orca Bio",
  GMAB: "Genmab",

  // ── Vaccines / infectious disease ─────────────────────────────────────────
  NVAX: "Novavax",
  BNTX: "BioNTech",
  CVAC: "CureVac",
  VXRT: "Vaxart",
  PCVX: "Vaxcyte",
  GOVX: "GeoVax Labs",
  MRNA: "ModernaTX",

  // ── Mega-cap pharma ───────────────────────────────────────────────────────
  REGN: "Regeneron Pharmaceuticals",
  AMGN: "Amgen",
  GILD: "Gilead Sciences",
  ABBV: "AbbVie",
  PFE:  "Pfizer",
  JNJ:  "Janssen Research",
  NVO:  "Novo Nordisk",
  LLY:  "Eli Lilly",
  AZN:  "AstraZeneca",
  BMY:  "Bristol-Myers Squibb",
  MRK:  "Merck Sharp",
  VRTX: "Vertex Pharmaceuticals",
  SNY:  "Sanofi",
  GSK:  "GlaxoSmithKline",
  NVS:  "Novartis",
  TAK:  "Takeda",
  RHHBY:"Hoffmann-La Roche",
  BAYRY:"Bayer",
  RPRX: "Royalty Pharma",
  LNTH: "Lantheus",
  UCB:  "UCB Pharma",
  GLPG: "Galapagos",

  // ── Diagnostics / tech ────────────────────────────────────────────────────
  RGEN: "Repligen",
  NVCR: "NovoCure",
  SDGR: "Schrödinger",
  ADPT: "Adaptive Biotechnologies",
  TWST: "Twist Bioscience",

  // ── Additional small/mid-cap biotech ──────────────────────────────────────
  PTGX: "Protagonist Therapeutics",
  MNKD: "MannKind Corporation",
  ZYME: "Zymeworks",
  LYEL: "Lyel Immunopharma",
  RCUS: "Arcus Biosciences",
  HOOK: "Hookipa Pharma",
  FATE: "Fate Therapeutics",
  NKTR: "Nektar Therapeutics",
  STRO: "Sutro Biopharma",
  AGEN: "Agenus",
  KROS: "Keros Therapeutics",
  CRNX: "Crinetics Pharmaceuticals",
  FULC: "Fulcrum Therapeutics",
  RVNC: "Revance Therapeutics",
  FGEN: "FibroGen",
  LNTH: "Lantheus",
  PASG: "Passage Bio",
  IPHA: "IO Biotech",
  CADL: "Candel Therapeutics",
  RVMD: "Revolution Medicines",

  // ── Additional rare/specialty ──────────────────────────────────────────────
  AVEO: "AVEO Pharmaceuticals",
  CORT: "Corcept Therapeutics",
  LGND: "Ligand Pharmaceuticals",
  HALO: "Halozyme Therapeutics",
  TBPH: "Theravance Biopharma",
  ACHC: "Achaogen",
  PRTK: "Paratek Pharmaceuticals",
  INVA: "Innoviva",
  SCPH: "scPharmaceuticals",
  SPPI: "Spectrum Pharmaceuticals",
  ANIK: "Anika Therapeutics",
  ATNM: "Actinium Pharmaceuticals",
  RVNC: "Revance Therapeutics",
  PRVB: "Provention Bio",
  IMRX: "Immuneering",
  IMGO: "Imago BioSciences",
  RDUS: "Radius Health",
  VSTM: "Verastem",
  SLNO: "Soleno Therapeutics",
  RLMD: "Relmada Therapeutics",
  PULM: "Pulmatrix",
  XCUR: "Exicure",
  RAPT: "RAPT Therapeutics",
  CLVT: "Clovis Oncology",
  HOOK: "Hookipa Pharma",
  PMVP: "PMV Pharmaceuticals",
  GRTS: "Gritstone Bio",
  MIRA: "Mirati Therapeutics",
  TARS: "Tarsus Pharmaceuticals",

  // ── International pharma ADRs ─────────────────────────────────────────────
  ZLAB: "Zymeworks",
  BGNE: "BeiGene",
  IMAB: "I-Mab",
  ZLAB: "Zai Lab",
  LEGN: "Legend Biotech",
  ARGX: "argenx",
  GLPG: "Galapagos",
  NBTX: "Nanobiotix",
  STLAM:"Stallergenes Greer",
  MRUS: "Merus",
  BCYC: "Bicycle Therapeutics",
  IMTX: "Immatics",
  GMAB: "Genmab",
  UCB:  "UCB",

  // ── Platform / diversified ────────────────────────────────────────────────
  SDGR: "Schrödinger",
  RXRX: "Recursion Pharmaceuticals",
  ABCL: "AbCellera",
  ADPT: "Adaptive Biotechnologies",

  // ── Additional oncology ───────────────────────────────────────────────────
  AGIO: "Agios Pharmaceuticals",
  EPZM: "Epizyme",
  KPTI: "Karyopharm Therapeutics",
  SYRS: "Syros Pharmaceuticals",
  ZNTL: "Zentalis Pharmaceuticals",
  PRME: "Prime Medicine",
  KURA: "Kura Oncology",
  GPCR: "Structure Therapeutics",
  ONCT: "Oncternal Therapeutics",
  KRON: "Kronos Bio",
  IKTX: "Ikena Oncology",
  JANX: "Janux Therapeutics",
  ITOS: "iTeos Therapeutics",
  ACET: "Adicet Bio",
  XBIA: "Xilio Therapeutics",

  // ── Metabolic / endocrine ─────────────────────────────────────────────────
  RYTM: "Rhythm Pharmaceuticals",
  KDNY: "Chinook Therapeutics",
  CRNX: "Crinetics Pharmaceuticals",
  AKBA: "Akebia Therapeutics",
  AMRN: "Amarin",
  LXRX: "Lexicon Pharmaceuticals",
  ESPR: "Esperion Therapeutics",
  ETNB: "89bio",
  MDGL: "Madrigal Pharmaceuticals",
  VKTX: "Viking Therapeutics",
  VRNA: "Verona Pharma",

  // ── Women's health / misc ─────────────────────────────────────────────────
  ORGN: "Origin Agritech",
  OVID: "Ovid Therapeutics",
  PHAT: "Pharvaris",

  // ── Dermatology ───────────────────────────────────────────────────────────
  ARQT: "Arcutis Biotherapeutics",
  KRYS: "Krystal Biotech",

  // ── Ophthalmology ────────────────────────────────────────────────────────
  ISEE: "Iveric Bio",
  QURE: "uniQure",
  EDIT: "Editas Medicine",
  OCGN: "Ocugen",

  // ── Additional mid-cap ────────────────────────────────────────────────────
  TARS: "Tarsus Pharmaceuticals",
  TNGX: "Tango Therapeutics",
  RLAY: "Relay Therapeutics",
  NUVL: "Nuvalent",
  ERAS: "Erasca",
  ALXO: "ALX Oncology",
  TYRA: "Tyra Biosciences",
  DAWN: "Day One Biopharmaceuticals",
  ANNX: "Annexon Biosciences",
  ALLK: "Allakos",
  ALPN: "Alpine Immune Sciences",
  ALDX: "Aldeyra Therapeutics",

  // ── Oncology (additional) ─────────────────────────────────────────────────
  ACLX: "Arcellx",
  BPMC: "Blueprint Medicines",
  BTAI: "BioAtla",
  CGEM: "Cullinan Oncology",
  CGON: "CG Oncology",
  COGT: "Cogent Biosciences",
  CRVS: "Corvus Pharmaceuticals",
  CRDF: "Cardiff Oncology",
  DTIL: "Precision BioSciences",
  ELVN: "Elevation Oncology",
  ENLV: "Enlivex Therapeutics",
  IGMS: "IGM Biosciences",
  IMMO: "Immunome",
  JNCE: "Jounce Therapeutics",
  LPTX: "Leap Therapeutics",
  MEIP: "MEI Pharma",
  MESO: "Mesoblast",
  MORF: "Morphic Therapeutic",
  MRSN: "Mersana Therapeutics",
  MTEM: "Molecular Templates",
  NKTX: "Nkarta",
  NUVB: "Nuvation Bio",
  PRLD: "Prelude Therapeutics",
  RPTX: "Repare Therapeutics",
  SURF: "Surface Oncology",
  TCRT: "Alaunos Therapeutics",
  TPST: "Tempest Therapeutics",
  APGE: "Apogee Therapeutics",
  HTBX: "Heat Biologics",
  MAIA: "MAIA Biotechnology",
  MNPR: "Monopar Therapeutics",

  // ── Cardio / metabolic / renal (additional) ───────────────────────────────
  AKRO: "Akero Therapeutics",
  CYTK: "Cytokinetics",
  LQDA: "Liquidia Technologies",
  VERA: "Vera Therapeutics",
  CPRX: "Catalyst Pharmaceuticals",
  IRWD: "Ironwood Pharmaceuticals",

  // ── Neurology / CNS (additional) ──────────────────────────────────────────
  ANVS: "Annovis Bio",
  ATHA: "Athira Pharma",
  AVXL: "Anavex Life Sciences",
  CMPS: "COMPASS Pathways",
  CYCN: "Cyclerion Therapeutics",
  MNOV: "MediciNova",
  NERV: "Minerva Neurosciences",
  QNCX: "Quince Therapeutics",
  VCNX: "Vaccinex",

  // ── Rare / gene / cell therapy (additional) ───────────────────────────────
  ALGS: "Aligos Therapeutics",
  BLCM: "Bellicum Pharmaceuticals",
  CLRB: "Cellectar Biosciences",
  HUMA: "Humacyte",
  LCTX: "Lineage Cell Therapeutics",
  MTNB: "Matinas BioPharma",
  STOK: "Stoke Therapeutics",
  VCEL: "Vericel",

  // ── Immunology / inflammation (additional) ────────────────────────────────
  ABUS: "Arbutus Biopharma",
  AFMD: "Affimed",
  AUPH: "Aurinia Pharmaceuticals",
  BCRX: "BioCryst Pharmaceuticals",
  IFRX: "InflaRx",
  MCRB: "Seres Therapeutics",
  OMER: "Omeros Corporation",
  PYPD: "PolyPid",

  // ── Infectious disease / vaccines (additional) ────────────────────────────
  AVIR: "Atea Pharmaceuticals",
  DVAX: "Dynavax Technologies",
  EIGR: "Eiger BioPharmaceuticals",
  IVVD: "Invivyd",
  SIGA: "SIGA Technologies",

  // ── Ophthalmology (additional) ────────────────────────────────────────────
  EYEN: "Eyenovia",
  HROW: "Harrow Health",
  KALA: "Kala Bio",
  KALV: "KalVista Pharmaceuticals",
  OCUL: "Ocular Therapeutix",

  // ── Respiratory / pulmonary ───────────────────────────────────────────────
  SVRA: "Savara",
  WINT: "Windtree Therapeutics",

  // ── Diagnostics / liquid biopsy ───────────────────────────────────────────
  EXAS: "Exact Sciences",
  FLGT: "Fulgent Genetics",
  GH:   "Guardant Health",
  SEER: "Seer Bio",

  // ── Specialty pharma / other ──────────────────────────────────────────────
  ACER: "Acer Therapeutics",
  ALIM: "Alimera Sciences",
  ALRN: "Aileron Therapeutics",
  AMRX: "Amneal Pharmaceuticals",
  ANIP: "ANI Pharmaceuticals",
  APLT: "Applied Therapeutics",
  APTO: "Aptose Biosciences",
  APVO: "Aptevo Therapeutics",
  AQST: "Aquestive Therapeutics",
  ASRT: "Assertio Holdings",
  ATXI: "Avenue Therapeutics",
  AVDL: "Avadel Pharmaceuticals",
  AYTU: "Aytu BioPharma",
  BYSI: "BeyondSpring",
  CARA: "Cara Therapeutics",
  CBMG: "Cellular Biomedicine Group",
  CHRS: "Coherus BioSciences",
  CMRX: "Chembio Diagnostics",
  CNSP: "CNS Pharmaceuticals",
  CNTB: "Connect Biopharma",
  EVFM: "Evofem Biosciences",
  FBIO: "Fortress Biotech",
  GALT: "Galectin Therapeutics",
  GLYC: "GlycoMimetics",
  GOSS: "Gossamer Bio",
  HRTX: "Heron Therapeutics",
  INFI: "Infinity Pharmaceuticals",
  ITRM: "Iterion Therapeutics",
  KRTX: "Karuna Therapeutics",
  LPCN: "Lipocine",
  LTRN: "Lantern Pharma",
  LYRA: "Lyra Therapeutics",
  MRNS: "Marinus Pharmaceuticals",
  NLSP: "NLS Pharmaceutics",
  NMTR: "9 Meters Biopharma",
  NOVN: "Novan",
  NRBO: "NeuroBo Pharmaceuticals",
  ONCS: "OncoSec Medical",
  ORGO: "Organogenesis",
  ORMP: "Oramed Pharmaceuticals",
  PCRX: "Pacira BioSciences",
  SUPN: "Supernus Pharmaceuticals",
  TNXP: "Tonix Pharmaceuticals",
  VERU: "Veru",
  XFOR: "X4 Pharmaceuticals",
};
