// companies.js — Ticker → CT.gov sponsor search term (deduplicated)
// Values are the shortest reliable string that CT.gov's query.spons will match.

window.EXTRA_COMPANIES = {

  // ── Large-cap / specialty pharma ──────────────────────────────────────────
  REGN:  "Regeneron Pharmaceuticals",
  AMGN:  "Amgen",
  GILD:  "Gilead Sciences",
  ABBV:  "AbbVie",
  PFE:   "Pfizer",
  JNJ:   "Janssen Research",
  NVO:   "Novo Nordisk",
  LLY:   "Eli Lilly",
  AZN:   "AstraZeneca",
  BMY:   "Bristol-Myers Squibb",
  MRK:   "Merck Sharp",
  VRTX:  "Vertex Pharmaceuticals",
  SNY:   "Sanofi",
  GSK:   "GlaxoSmithKline",
  NVS:   "Novartis",
  TAK:   "Takeda",
  RHHBY: "Hoffmann-La Roche",
  BAYRY: "Bayer",
  RPRX:  "Royalty Pharma",
  UCB:   "UCB Pharma",
  BMRN:  "BioMarin Pharmaceutical",
  ARGX:  "argenx",
  ALNY:  "Alnylam Pharmaceuticals",
  ALKS:  "Alkermes",
  JAZZ:  "Jazz Pharmaceuticals",
  UTHR:  "United Therapeutics",
  NKTR:  "Nektar Therapeutics",
  INCY:  "Incyte",
  EXEL:  "Exelixis",
  NBIX:  "Neurocrine Biosciences",
  ACAD:  "ACADIA Pharmaceuticals",
  IONS:  "Ionis Pharmaceuticals",
  ARWR:  "Arrowhead Pharmaceuticals",
  LNTH:  "Lantheus",
  RGEN:  "Repligen",
  NVCR:  "NovoCure",
  HALO:  "Halozyme Therapeutics",
  PCRX:  "Pacira BioSciences",
  SUPN:  "Supernus Pharmaceuticals",
  CORT:  "Corcept Therapeutics",
  LGND:  "Ligand Pharmaceuticals",
  INVA:  "Innoviva",

  // Acquired / delisted — trials may still appear in CT.gov archives
  HZNP:  "Horizon Therapeutics",       // acquired by Amgen 2023
  SGEN:  "Seagen",                     // acquired by Pfizer 2023
  KRTX:  "Karuna Therapeutics",        // acquired by BMS 2024

  // ── Neurology / CNS ───────────────────────────────────────────────────────
  BIIB:  "Biogen",
  DNLI:  "Denali Therapeutics",
  ALEC:  "Alector",
  PRAX:  "Praxis Precision Medicines",
  AXSM:  "Axsome Therapeutics",
  ITCI:  "Intra-Cellular Therapies",
  LBPH:  "Longboard Pharmaceuticals",
  MNMD:  "Mind Medicine",
  OVID:  "Ovid Therapeutics",
  RLMD:  "Relmada Therapeutics",
  SAVA:  "Cassava Sciences",
  VNDA:  "Vanda Pharmaceuticals",
  BHVN:  "Biohaven",
  ATNM:  "Actinium Pharmaceuticals",
  NRXP:  "NRx Pharmaceuticals",
  ANVS:  "Annovis Bio",
  ATHA:  "Athira Pharma",
  AVXL:  "Anavex Life Sciences",
  CMPS:  "COMPASS Pathways",
  CYCN:  "Cyclerion Therapeutics",
  MNOV:  "MediciNova",
  NERV:  "Minerva Neurosciences",
  QNCX:  "Quince Therapeutics",
  VCNX:  "Vaccinex",
  MRNS:  "Marinus Pharmaceuticals",
  CNSP:  "CNS Pharmaceuticals",
  NRBO:  "NeuroBo Pharmaceuticals",

  // Acquired / delisted
  SAGE:  "Sage Therapeutics",          // acquired by Biogen 2023
  CERE:  "Cerevel Therapeutics",       // acquired by AbbVie 2024

  // ── Oncology ─────────────────────────────────────────────────────────────
  SMMT:  "Summit Therapeutics",
  TGTX:  "TG Therapeutics",
  GTHX:  "G1 Therapeutics",
  IDYA:  "IDEAYA Biosciences",
  ORIC:  "Oric Pharmaceuticals",
  IMTX:  "Immatics",
  NBTX:  "Nanobiotix",
  BCYC:  "Bicycle Therapeutics",
  ATRA:  "Atara Biotherapeutics",
  MRUS:  "Merus",
  PRME:  "Prime Medicine",
  TYRA:  "Tyra Biosciences",
  DAWN:  "Day One Biopharmaceuticals",
  DCPH:  "Deciphera Pharmaceuticals",
  KURA:  "Kura Oncology",
  RCKT:  "Rocket Pharmaceuticals",
  OCGN:  "Ocugen",
  GPCR:  "Structure Therapeutics",
  ITOS:  "iTeos Therapeutics",
  JANX:  "Janux Therapeutics",
  ACET:  "Adicet Bio",
  ALLK:  "Allakos",
  ALDX:  "Aldeyra Therapeutics",
  ANNX:  "Annexon Biosciences",
  ASMB:  "Assembly Biosciences",
  ABCL:  "AbCellera Biologics",
  PULM:  "Pulmatrix",
  IKTX:  "Ikena Oncology",
  PMVP:  "PMV Pharmaceuticals",
  ONCT:  "Oncternal Therapeutics",
  KRON:  "Kronos Bio",
  MDNA:  "Medicenna Therapeutics",
  EDSA:  "Edesa Biotech",
  CABA:  "Cabaletta Bio",
  XBIA:  "Xilio Therapeutics",
  ZNTL:  "Zentalis Pharmaceuticals",
  LRMR:  "Larimar Therapeutics",
  IMVT:  "Immunovant",
  IMCR:  "Immunocore",
  KYMR:  "Kymera Therapeutics",
  NRIX:  "Nurix Therapeutics",
  TNGX:  "Tango Therapeutics",
  RLAY:  "Relay Therapeutics",
  ERAS:  "Erasca",
  NUVL:  "Nuvalent",
  MGNX:  "MacroGenics",
  SYRS:  "Syros Pharmaceuticals",
  RAPT:  "RAPT Therapeutics",
  LYEL:  "Lyell Immunopharma",
  ALXO:  "ALX Oncology",
  STRO:  "Sutro Biopharma",
  AGEN:  "Agenus",
  KPTI:  "Karyopharm Therapeutics",
  ACLX:  "Arcellx",
  BPMC:  "Blueprint Medicines",
  BTAI:  "BioAtla",
  CGEM:  "Cullinan Oncology",
  CGON:  "CG Oncology",
  COGT:  "Cogent Biosciences",
  CRVS:  "Corvus Pharmaceuticals",
  CRDF:  "Cardiff Oncology",
  DTIL:  "Precision BioSciences",
  ELVN:  "Elevation Oncology",
  ENLV:  "Enlivex Therapeutics",
  IGMS:  "IGM Biosciences",
  IMMO:  "Immunome",
  LPTX:  "Leap Therapeutics",
  MEIP:  "MEI Pharma",
  MESO:  "Mesoblast",
  MORF:  "Morphic Therapeutic",
  MRSN:  "Mersana Therapeutics",
  MTEM:  "Molecular Templates",
  NKTX:  "Nkarta",
  NUVB:  "Nuvation Bio",
  PRLD:  "Prelude Therapeutics",
  RPTX:  "Repare Therapeutics",
  SURF:  "Surface Oncology",
  TCRT:  "Alaunos Therapeutics",
  TPST:  "Tempest Therapeutics",
  APGE:  "Apogee Therapeutics",
  HTBX:  "Heat Biologics",
  MAIA:  "MAIA Biotechnology",
  MNPR:  "Monopar Therapeutics",
  TARS:  "Tarsus Pharmaceuticals",
  VSTM:  "Verastem",
  XCUR:  "Exicure",
  SPPI:  "Spectrum Pharmaceuticals",

  // Acquired / delisted
  IMGN:  "ImmunoGen",                  // acquired by AbbVie 2024
  EPZM:  "Epizyme",                    // acquired by Ipsen 2022
  MIRA:  "Mirati Therapeutics",        // acquired by BMS 2024
  KDNY:  "Chinook Therapeutics",       // acquired by Novartis 2023
  ALPN:  "Alpine Immune Sciences",     // acquired by Vertex 2024
  CLVT:  "Clovis Oncology",           // bankruptcy 2022
  GRPH:  "Graphite Bio",              // acquired by Kamau Therapeutics 2023
  JNCE:  "Jounce Therapeutics",       // merged with Redx Pharma 2024

  // ── Rare disease / genetics ───────────────────────────────────────────────
  ASND:  "Ascendis Pharma",
  BBIO:  "BridgeBio Pharma",
  BLUE:  "bluebird bio",
  SRPT:  "Sarepta Therapeutics",
  RARE:  "Ultragenyx Pharmaceutical",
  FOLD:  "Amicus Therapeutics",
  BEAM:  "Beam Therapeutics",
  EDIT:  "Editas Medicine",
  CRSP:  "CRISPR Therapeutics",
  NTLA:  "Intellia Therapeutics",
  QURE:  "uniQure",
  SLDB:  "Solid Biosciences",
  TRDA:  "Entrada Therapeutics",
  TVTX:  "Travere Therapeutics",
  PLRX:  "Pliant Therapeutics",
  PRTA:  "Prothena",
  PTCT:  "PTC Therapeutics",
  RYTM:  "Rhythm Pharmaceuticals",
  PHAT:  "Pharvaris",
  GERN:  "Geron Corporation",
  KRYS:  "Krystal Biotech",
  GRTS:  "Gritstone Bio",
  SNDX:  "Syndax Pharmaceuticals",
  MGTX:  "MeiraGTx",
  MIRM:  "Mirum Pharmaceuticals",
  LEGN:  "Legend Biotech",
  YMAB:  "Y-mAbs Therapeutics",
  RXRX:  "Recursion Pharmaceuticals",
  SPRB:  "Spruce Biosciences",
  ALGS:  "Aligos Therapeutics",
  BLCM:  "Bellicum Pharmaceuticals",
  CLRB:  "Cellectar Biosciences",
  HUMA:  "Humacyte",
  LCTX:  "Lineage Cell Therapeutics",
  MTNB:  "Matinas BioPharma",
  STOK:  "Stoke Therapeutics",
  VCEL:  "Vericel",
  PTGX:  "Protagonist Therapeutics",
  KROS:  "Keros Therapeutics",
  CRNX:  "Crinetics Pharmaceuticals",
  SLNO:  "Soleno Therapeutics",
  ANIK:  "Anika Therapeutics",
  IMRX:  "Immuneering",

  // Acquired / delisted
  ACHC:  "Achaogen",                   // bankruptcy 2019
  RDUS:  "Radius Health",              // went private 2022
  PRVB:  "Provention Bio",             // acquired by Sanofi 2023
  IMGO:  "Imago BioSciences",          // acquired by Merck 2023

  // ── Immunology / inflammation ─────────────────────────────────────────────
  ANAB:  "AnaptysBio",
  APLS:  "Apellis Pharmaceuticals",
  ARDX:  "Ardelyx",
  ARQT:  "Arcutis Biotherapeutics",
  SELB:  "Selecta Biosciences",
  XNCR:  "Xencor",
  CLDX:  "Celldex Therapeutics",
  VRDN:  "Viridian Therapeutics",
  HOOK:  "Hookipa Pharma",
  ALLO:  "Allogene Therapeutics",
  ROIV:  "Roivant Sciences",
  ARVN:  "Arvinas",
  ABUS:  "Arbutus Biopharma",
  AFMD:  "Affimed",
  AUPH:  "Aurinia Pharmaceuticals",
  BCRX:  "BioCryst Pharmaceuticals",
  IFRX:  "InflaRx",
  MCRB:  "Seres Therapeutics",
  OMER:  "Omeros Corporation",
  PYPD:  "PolyPid",

  // ── Cardiology / metabolic / renal ───────────────────────────────────────
  ETNB:  "89bio",
  MDGL:  "Madrigal Pharmaceuticals",
  VKTX:  "Viking Therapeutics",
  VRNA:  "Verona Pharma",
  AMRN:  "Amarin Corporation",
  AKBA:  "Akebia Therapeutics",
  LXRX:  "Lexicon Pharmaceuticals",
  ESPR:  "Esperion Therapeutics",
  KMPH:  "Coeptis Therapeutics",
  AKRO:  "Akero Therapeutics",
  CYTK:  "Cytokinetics",
  LQDA:  "Liquidia Technologies",
  VERA:  "Vera Therapeutics",
  CPRX:  "Catalyst Pharmaceuticals",
  IRWD:  "Ironwood Pharmaceuticals",
  AGIO:  "Agios Pharmaceuticals",
  TBPH:  "Theravance Biopharma",
  AMRX:  "Amneal Pharmaceuticals",
  ANIP:  "ANI Pharmaceuticals",

  // ── Gene / cell therapy ───────────────────────────────────────────────────
  AUTL:  "Autolus Therapeutics",
  CLLS:  "Cellectis",
  VERV:  "Verve Therapeutics",
  RNA:   "Avidity Biosciences",
  SANA:  "Sana Biotechnology",
  ORCA:  "Orca Bio",
  GMAB:  "Genmab",
  FATE:  "Fate Therapeutics",
  RCUS:  "Arcus Biosciences",
  FULC:  "Fulcrum Therapeutics",

  // ── Vaccines / infectious disease ─────────────────────────────────────────
  MRNA:  "ModernaTX",
  NVAX:  "Novavax",
  BNTX:  "BioNTech",
  CVAC:  "CureVac",
  VXRT:  "Vaxart",
  PCVX:  "Vaxcyte",
  GOVX:  "GeoVax Labs",
  AVIR:  "Atea Pharmaceuticals",
  DVAX:  "Dynavax Technologies",
  EIGR:  "Eiger BioPharmaceuticals",
  IVVD:  "Invivyd",
  SIGA:  "SIGA Technologies",

  // ── Ophthalmology ─────────────────────────────────────────────────────────
  EYEN:  "Eyenovia",
  HROW:  "Harrow Health",
  KALA:  "Kala Bio",
  KALV:  "KalVista Pharmaceuticals",
  OCUL:  "Ocular Therapeutix",

  // Acquired / delisted
  ISEE:  "Iveric Bio",                 // acquired by Astellas 2023

  // ── Respiratory / pulmonary ───────────────────────────────────────────────
  SVRA:  "Savara",
  WINT:  "Windtree Therapeutics",

  // ── Diagnostics / genomics ────────────────────────────────────────────────
  RGEN:  "Repligen",
  NVCR:  "NovoCure",
  SDGR:  "Schrödinger",
  ADPT:  "Adaptive Biotechnologies",
  TWST:  "Twist Bioscience",
  EXAS:  "Exact Sciences",
  FLGT:  "Fulgent Genetics",
  GH:    "Guardant Health",
  SEER:  "Seer Bio",

  // ── International ADRs ───────────────────────────────────────────────────
  ZLAB:  "Zai Lab",
  BGNE:  "BeiGene",
  STLAM: "Stallergenes Greer",
  GLPG:  "Galapagos",
  MRUS:  "Merus",

  // Acquired / delisted
  IMAB:  "I-Mab",                      // delisted from NASDAQ 2024

  // ── Watchlist defaults ────────────────────────────────────────────────────
  PASG:  "Passage Bio",
  IPHA:  "IO Biotech",
  CADL:  "Candel Therapeutics",
  RVMD:  "Revolution Medicines",
  MNKD:  "MannKind Corporation",
  ZYME:  "Zymeworks",
  FGEN:  "FibroGen",
  RVNC:  "Revance Therapeutics",
  PRTK:  "Paratek Pharmaceuticals",
  SCPH:  "scPharmaceuticals",
  VSTM:  "Verastem",

  // ── Specialty pharma / misc ───────────────────────────────────────────────
  ACER:  "Acer Therapeutics",
  ALIM:  "Alimera Sciences",
  ALRN:  "Aileron Therapeutics",
  APLT:  "Applied Therapeutics",
  APTO:  "Aptose Biosciences",
  APVO:  "Aptevo Therapeutics",
  AQST:  "Aquestive Therapeutics",
  ASRT:  "Assertio Holdings",
  ATXI:  "Avenue Therapeutics",
  AVDL:  "Avadel Pharmaceuticals",
  AYTU:  "Aytu BioPharma",
  BYSI:  "BeyondSpring",
  CARA:  "Cara Therapeutics",
  CBMG:  "Cellular Biomedicine Group",
  CHRS:  "Coherus BioSciences",
  CMRX:  "Chembio Diagnostics",
  CNTB:  "Connect Biopharma",
  EVFM:  "Evofem Biosciences",
  FBIO:  "Fortress Biotech",
  GALT:  "Galectin Therapeutics",
  GLYC:  "GlycoMimetics",
  GOSS:  "Gossamer Bio",
  HRTX:  "Heron Therapeutics",
  INFI:  "Infinity Pharmaceuticals",
  ITRM:  "Iterion Therapeutics",
  LPCN:  "Lipocine",
  LTRN:  "Lantern Pharma",
  LYRA:  "Lyra Therapeutics",
  NLSP:  "NLS Pharmaceutics",
  NMTR:  "9 Meters Biopharma",
  NOVN:  "Novan",
  ONCS:  "OncoSec Medical",
  ORGO:  "Organogenesis",
  ORMP:  "Oramed Pharmaceuticals",
  TNXP:  "Tonix Pharmaceuticals",
  VERU:  "Veru",
  XFOR:  "X4 Pharmaceuticals",
  AVEO:  "AVEO Pharmaceuticals",       // acquired by LG Chem 2022
};
